### ISSUE TITLE
Не находит игру в каталоге

### ISSUE THREAD

**Issue by katerina331** [katerina331/Team-diplom#1]
# Описание
При поиске созданного объекта игры в каталоге не получаем true

# Локализация дефекта
https://github.com/katerina331/Team-diplom/blob/01ed9b801fbb6bc5392a72f518ef7eab70128408/src/main/java/ru/netology/GameStore.java#L33

# Шаги воспроизведения
1. Открыть код программы в IDEA
1. Создаем тест
1. Добавить игру "Нетология Баттл Онлайн" с жанром "Аркады"
1. Проверяем наличие игры в каталоге
1. Запускаем тест
1. Смотрим на результат теста

*Ожидаемый результат:* тест пройден. Результат проверки наличия игры в каталоге - true
*Фактический результат:* тест упал. Результат проверки наличия игры в каталоге - false

# Скриншот
![image](https://user-images.githubusercontent.com/121889661/228596471-37560c0a-c17d-4ed5-b2e7-33cf0f447056.png)

# Окружение
* **Операционная система:** Windows 10 Pro 22H2
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** corretto-11

@Sergey-Zhuravlev-Test

**Comment by Sergey-Zhuravlev-Test** [comment]
## Исправлен метод

https://github.com/katerina331/Team-diplom/blob/de590ef21e23cf48c5f796bf408e77f15f6d11f0/src/main/java/ru/netology/GameStore.java#L32

Он был написан с ошибкой, из него постоянно возвращалось значение false

## Тест проходит
