### ISSUE TITLE
Не покрыта часть кода тестами

### ISSUE THREAD

**Issue by katerina331** [katerina331/Team-diplom#11]
# Описание
Часть нового кода не покрыта тестами

# Локализация дефекта
https://github.com/katerina331/Team-diplom/blob/bcbe7e8b81ee72976651bd2c1bae5c8b9395a223/src/main/java/ru/netology/Player.java#L84

# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Запускаем verife
1. Смотрим на результат jacoco

*Ожидаемый результат:* код покрыт тестами больше 0.90
*Фактический результат:* код покрыт тестами 0.88

# Скриншот
![image](https://user-images.githubusercontent.com/121889661/230479305-4f39e4a7-ac50-46c3-be4a-51e59a402e70.png)

# Окружение
* **Операционная система:** Windows 10 Pro 22H2
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** corretto-11

@Sergey-Zhuravlev-Test

**Comment by Sergey-Zhuravlev-Test** [comment]
## Добавлен тест
https://github.com/katerina331/Team-diplom/blob/467919e9fcefb95445602cdbbfd808e6a316b819/src/test/java/ru/netology/PlayerTest.java#L63
