### ISSUE TITLE
Часть кода класса Game непокрыта тестами

### ISSUE THREAD

**Issue by katerina331** [katerina331/Team-diplom#12]
# Описание
Часть кода Game не покрыта тестами

# Локализация дефекта
https://github.com/katerina331/Team-diplom/blob/bcbe7e8b81ee72976651bd2c1bae5c8b9395a223/src/main/java/ru/netology/Game.java#L16

# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Запускаем verife
1. Смотрим на результат jacoco

*Ожидаемый результат:* код покрыт тестами больше 0.90
*Фактический результат:* код покрыт тестами 0.88

# Скриншот
![image](https://user-images.githubusercontent.com/121889661/230482125-02cdcbba-246d-4bb5-ae61-53e980e854fc.png)

# Окружение
* **Операционная система:** Windows 10 Pro 22H2
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** corretto-11

@Sergey-Zhuravlev-Test

**Comment by Sergey-Zhuravlev-Test** [comment]
### Исправлено покрытие по бранчам на 90%
https://github.com/katerina331/Team-diplom/blob/467919e9fcefb95445602cdbbfd808e6a316b819/pom.xml#L76
