### ISSUE TITLE
Не суммирует количество времени для одного игрока

### ISSUE THREAD

**Issue by katerina331** [katerina331/Team-diplom#2]
# Описание
Добавляя игроку время в игре получаем 0 при вызове общего количества времени

# Локализация дефекта
https://github.com/katerina331/Team-diplom/blob/01ed9b801fbb6bc5392a72f518ef7eab70128408/src/main/java/ru/netology/GameStore.java#L76

# Шаги воспроизведения
1. Открыть код программы в IDEA
1. Создаем тест
1. Добавляем одного игрока "Коля" с времинем 10
1. Проверяем сумму времени игры в каталоге
1. Запускаем тест
1. Смотрим на результат теста

*Ожидаемый результат:* тест пройден. Результат суммы времени игр в каталоге - 10
*Фактический результат:* тест упал. Результат суммы времени игр в каталоге - 0

# Скриншот
![image](https://user-images.githubusercontent.com/121889661/227774683-a343a0ea-c450-4062-b59c-f2d8e0eed891.png)

# Окружение
* **Операционная система:** Windows 10 Pro 22H2
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** corretto-11

@Sergey-Zhuravlev-Test

**Comment by Sergey-Zhuravlev-Test** [comment]
## Написан метод суммирования времени игры

https://github.com/katerina331/Team-diplom/blob/de590ef21e23cf48c5f796bf408e77f15f6d11f0/src/main/java/ru/netology/GameStore.java#L75

public int getSumPlayedTime() {
        int sum = 0;
        ArrayList<Integer> playedHours = new ArrayList<>(playedTime.values());
        for (Integer hours : playedHours) {
            sum += hours;
        }
        return sum; //написан метод суммирования времени игры bug #4 и bug #2
    }

## Тест проходит
