### ISSUE TITLE
Не добавляет время игрока 

### ISSUE THREAD

**Issue by katerina331** [katerina331/Team-diplom#3]
# Описание
Добавляя игроку время в игре дважды получаем 0 при вызове общего количества времени

# Локализация дефекта
https://github.com/katerina331/Team-diplom/blob/01ed9b801fbb6bc5392a72f518ef7eab70128408/src/main/java/ru/netology/GameStore.java#L48

# Шаги воспроизведения
1. Открыть код программы в IDEA
1. Создаем тест
1. Добавляем одного игрока "Коля" с временем 5
1. Добавляем время игроку "Коля" время 15
1. Проверяем сумму времени игры в каталоге
1. Запускаем тест
1. Смотрим на результат теста

*Ожидаемый результат:* тест пройден. Результат суммы времени игр в каталоге - 20
*Фактический результат:* тест упал. Результат суммы времени игр в каталоге - 0

# Скриншот
![image](https://user-images.githubusercontent.com/121889661/228626140-1515e259-f389-497c-80db-8042e191207b.png)

# Окружение
* **Операционная система:** Windows 10 Pro 22H2
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** corretto-11

@Sergey-Zhuravlev-Test

**Comment by Sergey-Zhuravlev-Test** [comment]
## Добавлен учет часов в методе https://github.com/katerina331/Team-diplom/blob/de590ef21e23cf48c5f796bf408e77f15f6d11f0/src/main/java/ru/netology/GameStore.java#L46

https://github.com/katerina331/Team-diplom/blob/de590ef21e23cf48c5f796bf408e77f15f6d11f0/src/main/java/ru/netology/GameStore.java#L48

## Тест проходит
