### ISSUE TITLE
Невозможно посчитать время игры по жанрам

### ISSUE THREAD

**Issue by Sergey-Zhuravlev-Test** [katerina331/Team-diplom#5]
## Описание

При использовании метода подсчета времени игры по жанрам проверка выдает ошибку

## Локализация дефекта

https://github.com/katerina331/Team-diplom/blob/7ecd9e8e655782bee095237d1c05d37c2e154d95/src/main/java/ru/netology/Player.java#L56

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/katerina331/Team-diplom/blob/player/src/test/java/ru/netology/PlayerTest.java) в IDEA
2. Запустить тест https://github.com/katerina331/Team-diplom/blob/7ecd9e8e655782bee095237d1c05d37c2e154d95/src/test/java/ru/netology/PlayerTest.java#L10
3. Запустить Debug этого теста
4. Посмотреть результат прохождения теста

***Ожидаемый результат***: тест пройден, на игру потрачено 3 часа
***Фактический результат***: тест провален, по подсчетам на игру потрачено 0 часов

## Скриншот

![image](https://user-images.githubusercontent.com/118224940/229307426-9e274356-510a-4352-a6a9-0d0586c83ce1.png)
![image](https://user-images.githubusercontent.com/118224940/229307485-03f807ae-3f96-4726-87a4-250963c560ba.png)

## Окружение

- Операционная система: Windows Версия	22H2 Сборка ОС 19045.2486 Взаимодействие Windows Feature Experience Pack 120.2212.4190.0
- IDE: IntelliJ IDEA 2022.3.1 (Community Edition)
- Java: openjdk version "11.0.17"

**Comment by katerina331** [comment]
В файле Player.java в строке 44 были внесены правки:
playedTime.put(game, playedTime.get(game) + hours)
добавлена (+ hours) - увеличения исходного времени на время hours

**Comment by katerina331** [comment]
В файле Player.java в 61 строке были внесены правки:
else {
sum = 0;
удалено лишнее условие
