### ISSUE TITLE
Нет возможности поиска игры в которую играли больше всего по времени

### ISSUE THREAD

**Issue by Sergey-Zhuravlev-Test** [katerina331/Team-diplom#6]
## Описание

При использовании метода поиска самой популярной игры поиск не происходит, метод не дописан

## Локализация дефекта

https://github.com/katerina331/Team-diplom/blob/7ecd9e8e655782bee095237d1c05d37c2e154d95/src/main/java/ru/netology/Player.java#L73

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/katerina331/Team-diplom/blob/player/src/test/java/ru/netology/PlayerTest.java) в IDEA
2. Запустить тест https://github.com/katerina331/Team-diplom/blob/7ecd9e8e655782bee095237d1c05d37c2e154d95/src/test/java/ru/netology/PlayerTest.java#L44
3. Запустить Debug этого теста
4. Посмотреть результат прохождения теста

***Ожидаемый результат***: тест пройден, самая продолжительная игра в жанре Симулятор - Гонки
***Фактический результат***: тест провален, актуальный результат подсчетов - значение null

## Скриншот

![image](https://user-images.githubusercontent.com/118224940/229308203-00d745a9-9bb5-44c3-8316-11361b595134.png)
![image](https://user-images.githubusercontent.com/118224940/229308246-b62331b9-a6c5-48bf-adab-22616b958f4e.png)

## Окружение

- Операционная система: Windows Версия	22H2 Сборка ОС 19045.2486 Взаимодействие Windows Feature Experience Pack 120.2212.4190.0
- IDE: IntelliJ IDEA 2022.3.1 (Community Edition)
- Java: openjdk version "11.0.17"

**Comment by katerina331** [comment]
В файле Player.java в строке 74 были внесены правки:
Game findGame = null;
int max = 0;
for (Game game : playedTime.keySet()) {
     if (game.getGenre().equals(genre)) {
         if (max < playedTime.get(game)) {
             max = playedTime.get(game);
             findGame = game;
         }
     }
}
return findGame;
дописан метод поиска игры по жанру с наибольшим временем
