### ISSUE TITLE
Нет ограничений на добавление игры, которая уже существует

### ISSUE THREAD

**Issue by Sergey-Zhuravlev-Test** [katerina331/Team-diplom#7]
## Описание

При использовании метода добавления игры в Мапу, нет проверки на то, что такая игра уже существует и ее данные должны остаться

## Локализация дефекта

https://github.com/katerina331/Team-diplom/blob/7ecd9e8e655782bee095237d1c05d37c2e154d95/src/main/java/ru/netology/Player.java#L29

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/katerina331/Team-diplom/blob/player/src/test/java/ru/netology/PlayerTest.java) в IDEA
2. Запустить тест https://github.com/katerina331/Team-diplom/blob/7ecd9e8e655782bee095237d1c05d37c2e154d95/src/test/java/ru/netology/PlayerTest.java#L81
3. Запустить Debug этого теста
4. Посмотреть результат прохождения теста

***Ожидаемый результат***: тест пройден, сохранились начальные данные по игре, количество потраченных часов 5
***Фактический результат***: тест провален, данные по игре обновились, количество потраченных часов 0

## Скриншот

![image](https://user-images.githubusercontent.com/118224940/229308814-40ec32cf-1602-4800-bb63-bcb178895359.png)
![image](https://user-images.githubusercontent.com/118224940/229308877-e69366e1-8c17-4451-8571-38a8ef9d6f71.png)

## Окружение

- Операционная система: Windows Версия	22H2 Сборка ОС 19045.2486 Взаимодействие Windows Feature Experience Pack 120.2212.4190.0
- IDE: IntelliJ IDEA 2022.3.1 (Community Edition)
- Java: openjdk version "11.0.17"

**Comment by katerina331** [comment]
В файле Player.java в строке 30 были внесены правки:
for (Game iGame : playedTime.keySet()) {
       if (!iGame.equals(game)) {
           playedTime.put(game, 0);
      }
}
добавлена (if (!iGame.equals(game))) - проверка на отсутствие игры

**Comment by katerina331** [comment]
В файле Player.java в строке 30 были внесены правки:
boolean noGame = true;
for (Game iGame : playedTime.keySet()) {
     if (iGame.equals(game)) {
         noGame=false;
     }
}
if (noGame) {
     playedTime.put(game, 0);
}
добавлена (if (iGame.equals(game))) - проверка на наличие игры
добавлено (boolean noGame = true;) - при условии пустого каталога
