### ISSUE TITLE
Не выкидывает исключение при отсутствии установленной игры

### ISSUE THREAD

**Issue by Sergey-Zhuravlev-Test** [katerina331/Team-diplom#8]
## Описание

Не прописан код на выброс исключение при отсутствии установленной игры через метод play

## Локализация дефекта

https://github.com/katerina331/Team-diplom/blob/7ecd9e8e655782bee095237d1c05d37c2e154d95/src/main/java/ru/netology/Player.java#L41

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/katerina331/Team-diplom/blob/player/src/test/java/ru/netology/PlayerTest.java) в IDEA
2. Запустить тест https://github.com/katerina331/Team-diplom/blob/7ecd9e8e655782bee095237d1c05d37c2e154d95/src/test/java/ru/netology/PlayerTest.java#L81
3. Запустить Debug этого теста
4. Посмотреть результат прохождения теста

***Ожидаемый результат***: тест пройден, появляется сообщение, что игра не была установлена
***Фактический результат***: тест провален, assertThrows не прошел

## Скриншот

![image](https://user-images.githubusercontent.com/118224940/229309345-05a363ab-ff14-4c91-b570-6e0ca605bb32.png)
![image](https://user-images.githubusercontent.com/118224940/229309382-b48c723f-a526-4f75-bd04-4233123ce3b2.png)

## Окружение

- Операционная система: Windows Версия	22H2 Сборка ОС 19045.2486 Взаимодействие Windows Feature Experience Pack 120.2212.4190.0
- IDE: IntelliJ IDEA 2022.3.1 (Community Edition)
- Java: openjdk version "11.0.17"

**Comment by katerina331** [comment]
В файле Player.java в строке 42 были внесены правки:
boolean noGame = true;
        for (Game iGame : playedTime.keySet()) {
            if (iGame.equals(game)) {
                noGame = false;
            }
        }
        if (noGame) {
            throw new RuntimeException("Игра " + game + "не установлена");
        }
добавлена ошибка на добавление времени неустановленной игре
