### ISSUE TITLE
Строка кода в методе Play класса Player не покрывается тестами

### ISSUE THREAD

**Issue by Sergey-Zhuravlev-Test** [katerina331/Team-diplom#9]
## Описание

При запуске команды mvn clean verify строка из метода
https://github.com/katerina331/Team-diplom/blob/2b1089e2e5aa6f5eed732ba5a4dfc2c3b024027c/src/main/java/ru/netology/Player.java#L49
не покрывается тестами

## Локализация дефекта

https://github.com/katerina331/Team-diplom/blob/2b1089e2e5aa6f5eed732ba5a4dfc2c3b024027c/src/main/java/ru/netology/Player.java#L63

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/katerina331/Team-diplom/blob/player/src/main/java/ru/netology/Player.java) в IDEA
2. Запустить тест проверку mvn clean verify
3. Запускаем файл index.html (target - site - index.html)
4. Посмотреть результат прохождения проверки

***Ожидаемый результат***: покрытие по бранчам в методе play 100%
***Фактический результат***: покрытие по бранчам в методе play 89%, сторока 63 в работе метода никогда не используется

## Скриншот

![image](https://user-images.githubusercontent.com/118224940/229627094-a9a6c8b5-f5f7-4f3f-a54c-95be565bfd1e.png)

## Окружение

- Операционная система: Windows Версия	22H2 Сборка ОС 19045.2486 Взаимодействие Windows Feature Experience Pack 120.2212.4190.0
- IDE: IntelliJ IDEA 2022.3.1 (Community Edition)
- Java: openjdk version "11.0.17"

**Comment by katerina331** [comment]
В файле Player.java в строке 54 были внесены правки:
} else {
    throw new RuntimeException("Игра " + game + "не установлена"); // исправлена! ошибка на добавление времени неустановленной игре
}
исправлен код на добавление ошибки отсутствия игры
